### ISSUE TITLE
A problem with the editor was detected.

### ISSUE THREAD

**Issue by Shedrel** [godot-mega-man/mega-man-maker-mmlv-editor#18]
I downloaded the previous editor _(v0.7.1)_, and the file **MMLV Editor_v0.8.0.pck** i renamed it to _MMLV Editor_v0.7.1.pck_ and ran it on _MMLV Editor_v0.7.1.exe_ (the previous editor) and it worked. It opened levels and save it too.
The problem is in the **editor** itself, from versions **0.8.0** and **0.8.1**.

**Comment by Firstject** [comment]
@Shedrel This proves to be useful for reproducing the bug. Thanks for sharing this! 👍👍

**Comment by Firstject** [comment]
This has been fixed. Closing.
