### ISSUE TITLE
Mixed up MM5 Backgrounds

### ISSUE THREAD

**Issue by Jevedor** [godot-mega-man/mega-man-maker-mmlv-editor#20]
When using backgrounds in MMLvE assigning background BgMM5Charge9 ID:72 will present as BgMM5Dark1-1 ID:329 in MMM.  Vice versa is also true.

**Steps to Reproduce**
1. Open MMM and create a room with the background BgMM5Dark1-1 ID:329
2. Save level
3. Open the level in MMLvE
4. The same room will display as BgMM5Charge9 ID:72
5. Change background back to BgMM5Dark1-1 ID:329
6. Save level
7. Reload level in MMM
8. The same room will display as BgMM5Charge9 ID:72

**Expected behavior**
The background stays consistent.  Seems like a misalignment with the background IDs

**Screenshots**

**Version number**
MMM 1.7.2
MMLvE 0.8.1

**Comment by Firstject** [comment]
Fixed. Thanks!
