### ISSUE TITLE
Some helpful information regarding the unable to load level bug

### ISSUE THREAD

**Issue by Jayjayjay3000** [godot-mega-man/mega-man-maker-mmlv-editor#21]
**Describe the bug**
This is the bug you stated you wanted information on in the 0.8.1 patch notes. Well, I believe I have something that will hopefully be helpful to you.

Although I'm sure you were already sent this, here is what the error message looks like:
![BugHelp](https://user-images.githubusercontent.com/32678728/106703422-cdb7f780-65af-11eb-96f0-fd96ca27137a.PNG)

**Steps to Reproduce**
Now, the interesting information. Since the error appeared with all of my levels, and the error message said "Could not open file at path", I supposed the problem was not with the level data itself, but rather the program's process for finding the data. Thinking this, I did some tests to see if I could get something else to happen:

Test 0: Normally opening the file via the "Open a File" menu.
Result: The error message above.

Test 1: Opening a file via the drag 'n' drop feature.
Result: The same error message.

Test 2: Since I stored the program on a flash drive (F:) and the level data is in the app data folder (in C:), I tried copying the level data to my flash drive and see if I could open that using the "Open a File" menu from there.
Result: It worked! No error message or really any differences.

Test 3: Similar to above, I opened the file from my flash drive, though this time I used the drag 'n' drop method.
Result: Similar error message to the one above. Here it is:
![BugHelp2](https://user-images.githubusercontent.com/32678728/106706696-ad8b3700-65b5-11eb-965c-90742e98e553.PNG)

Test 4: Seeing all this, I wondered if the problem was the program and the app data were in different directories (F: vs C:). Checking if this was the case, I copied the folder mmlv editor was in to C: and redid Test 0 with this new program.
Result: It works, just like it did in Test 2.

Test 5: Redid Test 1 with the program copy made in Test 4.
Result: Again, works.

Test 6: Redid Test 2 with the program copy made in Test 4.
Result: Also works.

Test 7: Redid Test 3 with the program copy made in Test 4.
Result: Interestingly, same error message as the one found in Test 3.

**Version number**
0.8.1

**Additional context**
I honestly don't have any additional information regarding this bug, though I hope what I was able to gather here helps you on fixing this. I hope you do well, and I hope you have a nice day/ night.

**Comment by Firstject** [comment]
Thanks for the info! I have investigated the issue and the problem is mainly from the code with unnecessary directory checks. This will get fixed soon, hopefully.
